#!/usr/bin/env python3
"""Step 3.3D min-token context-ID prompt dry-run audit. No API calls."""
from __future__ import annotations
import hashlib,importlib.util,json,re,statistics
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
BASE_SCRIPT=ROOT/'scripts/deepseek_l3_test20_dx_px_nonempty_context_id_prompt_audit/01_build_context_id_prompts_test20.py'
spec=importlib.util.spec_from_file_location('context_id_base',BASE_SCRIPT)
if spec is None or spec.loader is None:raise RuntimeError(f'Cannot load base prompt helpers: {BASE_SCRIPT}')
base=importlib.util.module_from_spec(spec);spec.loader.exec_module(base)
SELECTED=ROOT/'outputs/deepseek_l3_test20_dx_px_nonempty/selected_20_cases.jsonl';SOURCE=ROOT/'outputs/deepseek_l3_minimal_case_inputs/stay_level_all_minimal_for_llm_dx_px_nonempty.jsonl'
OLD=ROOT/'outputs/deepseek_l3_test20_dx_px_nonempty_prompt_audit/prompts_test20.jsonl';COMPACT=ROOT/'outputs/deepseek_l3_test20_dx_px_nonempty_prompt_compact_audit/prompts_test20_compact.jsonl';CONTEXT_ID=ROOT/'outputs/deepseek_l3_test20_dx_px_nonempty_context_id_prompt_audit/prompts_test20_context_id.jsonl'
OUT=ROOT/'outputs/deepseek_l3_test20_dx_px_nonempty_min_token_prompt_audit';PROMPTS=OUT/'prompts_test20_min_token.jsonl';REPORT=OUT/'min_token_prompt_audit_report.json';SAMPLE=OUT/'min_token_prompt_audit_sample.md';PROBLEMS=OUT/'min_token_prompt_problem_records.jsonl';VIEW=OUT/'selected_20_cases_min_token_prompt_view.jsonl'
SYSTEM_PROMPT='You are a clinical data attribution assistant for ICU medication recommendation research. eICU does not state true prescribing intent. For each medication, choose exactly one best anchor_id from D/P/L IDs in the given context, or null if no suitable anchor exists. Do not invent anchors or medications. Prefer diagnosis or physiological/lab anchors over medication-administration procedure anchors when both are plausible. Use cautious association wording, not causal treatment claims. Return JSON only.'
TASK='For each target medication, return one record. Medication must come from target_medications. For each medication, select exactly one best anchor_id from context IDs. anchor_id must be one D/P/L ID from context, or null if no suitable anchor exists. Do not output anchor strings, anchor types, full anchor objects, or multiple anchor IDs. Do not claim true prescribing intent. Avoid: was prescribed for, was given to treat, was used to treat, because the patient had, the reason is. Use cautious wording: is associated with, appears consistent with, may reflect, is plausibly linked to. Mention exact prescribing intent is not directly available from eICU. Return JSON only.'
OUTPUT={'stay_id':'string','hospital_id':'string','records':[{'medication':'from target_medications before |','medication_function':'from target_medications after |','anchor_id':'one D/P/L ID from context, or null','attribution_hypothesis':'cautious association; mention exact prescribing intent is not directly available from eICU'}]}
PATTERN=re.compile(r'^([DPL]\d+): (.+)$')

def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
 return h.hexdigest()
def short(prefix,items):return [f'{prefix}{i}: {text}' for i,text in enumerate(items,1)]
def build_context(c):return {'dx':short('D',c['dx']),'px':short('P',c['px']),'lab':short('L',c['lab'][:20])}
def parse_context(ctx):
 out={};kinds={'dx':'diagnosis','px':'procedure','lab':'lab'}
 for key,kind in kinds.items():
  for item in ctx[key]:
   m=PATTERN.fullmatch(item)
   if not m:raise ValueError(f'Invalid compact context item: {item}')
   out[m.group(1)]={'anchor_type':kind,'anchor_string':m.group(2)}
 return out
def restore_single_anchor(record,mapping):
 if 'anchor_ids' in record:return [],False,'schema_error_anchor_ids_array_forbidden'
 anchor_id=record.get('anchor_id')
 if anchor_id is None or anchor_id=='':return [],False,None
 if isinstance(anchor_id,(list,dict,tuple)):return [],False,'schema_error_multiple_anchor_value'
 if anchor_id not in mapping:return [],True,'illegal_anchor_id'
 return [{'anchor_id':anchor_id,'anchor_type':mapping[anchor_id]['anchor_type'],'anchor_string':mapping[anchor_id]['anchor_string']}],False,None
def load_chars(path):
 if not path.exists():return {}
 return {str(x.get('stay_id')):int(x.get('estimated_prompt_chars') or 0) for x in [json.loads(line) for line in path.read_text(encoding='utf-8').splitlines() if line.strip()]}
def write_jsonl(path,rows):path.write_text(''.join(json.dumps(x,ensure_ascii=False,allow_nan=False,separators=(',',':'))+'\n' for x in rows),encoding='utf-8')

def main():
 OUT.mkdir(parents=True,exist_ok=True);selected_hash=sha(SELECTED) if SELECTED.exists() else None;source_hash=sha(SOURCE);cases,used,input_path=base.load_cases();old=load_chars(OLD);compact=load_chars(COMPACT);contextid=load_chars(CONTEXT_ID);prompts=[];views=[];problems=[]
 for i,c in enumerate(cases,1):
  pid=f'test20_case_{i:03d}';ctx=build_context(c);mapping=parse_context(ctx);target=[f"{m['medication']}|{m['medication_function']}" for m in base.choose_meds(c)];user_obj={'case':{'stay_id':c['stay_id'],'hospital_id':c['hospital_id'],'age':c['age'],'sex':c['sex']},'context':ctx,'target_medications':target,'task':TASK,'output':OUTPUT};user=json.dumps(user_obj,ensure_ascii=False,allow_nan=False,separators=(',',':'));chars=len(SYSTEM_PROMPT)+len(user);oldc=old.get(c['stay_id'],0);compactc=compact.get(c['stay_id'],0);contextc=contextid.get(c['stay_id'],0);reduction=oldc-chars if oldc else 0;rate=reduction/oldc if oldc else 0.0
  row={'prompt_id':pid,'stay_id':c['stay_id'],'hospital_id':c['hospital_id'],'num_dx':len(ctx['dx']),'num_px':len(ctx['px']),'num_lab':len(ctx['lab']),'num_med':len(c['med']),'num_target_meds':len(target),'num_context_ids':len(mapping),'target_medications':target,'context':ctx,'anchor_id_map':mapping,'system_prompt':SYSTEM_PROMPT,'user_prompt':user,'estimated_prompt_chars':chars,'old_estimated_prompt_chars':oldc,'compact_estimated_prompt_chars':compactc,'context_id_estimated_prompt_chars':contextc,'char_reduction_vs_old':reduction,'char_reduction_rate_vs_old':rate,'dry_run_only':True};prompts.append(row);views.append({'prompt_id':pid,'stay_id':c['stay_id'],'hospital_id':c['hospital_id'],'target_medications':target,'context':ctx,'anchor_id_map':mapping})
  allitems=[(x,'D') for x in ctx['dx']]+[(x,'P') for x in ctx['px']]+[(x,'L') for x in ctx['lab']];ids=[];invalid=False
  for item,prefix in allitems:
   m=PATTERN.fullmatch(item);invalid|=not bool(m) or not m.group(1).startswith(prefix)
   if m:ids.append(m.group(1))
  restored,illegal,error=restore_single_anchor({'anchor_id':ids[0] if ids else None},mapping);null_restored,null_illegal,null_error=restore_single_anchor({'anchor_id':None},mapping);plural_restored,plural_illegal,plural_error=restore_single_anchor({'anchor_ids':ids[:2]},mapping)
  combined=(SYSTEM_PROMPT+user).casefold();checks=[('empty_dx',not ctx['dx']),('empty_px',not ctx['px']),('empty_med',not c['med']),('empty_target_med',not target),('empty_context_id',not ids),('duplicate_context_id',len(ids)!=len(set(ids))),('forbidden_field_found','condition_'+'group' in combined),('legacy_anchor_field_found','candidate_'+'anchors' in combined),('legacy_allowed_ids_field_found','allowed_'+'anchor_ids' in combined),('plural_anchor_ids_field_found','anchor_'+'ids' in combined),('id_text_object_found',any(isinstance(x,dict) for x,_ in allitems)),('invalid_context_string',invalid),('invalid_target_pipe',any(x.count('|')!=1 or not all(x.split('|')) for x in target)),('missing_anchor_id_constraint','anchor_id must be one d/p/l id from context, or null' not in combined),('missing_json_only_constraint','return json only' not in combined),('missing_prescribing_intent_warning','do not claim true prescribing intent' not in combined),('missing_anchor_output_constraint','exactly one best anchor_id' not in combined or 'do not output anchor strings, anchor types, full anchor objects, or multiple anchor ids' not in combined),('anchor_id_map_incomplete',set(mapping)!=set(ids)),('single_restore_failed',bool(ids) and (illegal or error or len(restored)!=1 or restored[0]['anchor_id']!=ids[0])),('null_restore_failed',null_restored!=[] or null_illegal or null_error is not None),('plural_schema_error_not_detected',plural_restored!=[] or plural_error!='schema_error_anchor_ids_array_forbidden')]
  for kind,bad in checks:
   if bad:problems.append({'prompt_id':pid,'stay_id':c['stay_id'],'problem_type':kind,'problem_detail':f'Min-token prompt audit failed: {kind}'})
 write_jsonl(PROMPTS,prompts);write_jsonl(VIEW,views);write_jsonl(PROBLEMS,problems)
 names=['empty_dx','empty_px','empty_med','empty_target_med','empty_context_id','duplicate_context_id','forbidden_field_found','legacy_anchor_field_found','legacy_allowed_ids_field_found','plural_anchor_ids_field_found','id_text_object_found','missing_anchor_id_constraint','missing_json_only_constraint','missing_prescribing_intent_warning'];counts={k:sum(x['problem_type']==k for x in problems) for k in names};chars=[x['estimated_prompt_chars'] for x in prompts];oldvals=[x['old_estimated_prompt_chars'] for x in prompts if x['old_estimated_prompt_chars']];compactvals=[x['compact_estimated_prompt_chars'] for x in prompts if x['compact_estimated_prompt_chars']];contextvals=[x['context_id_estimated_prompt_chars'] for x in prompts if x['context_id_estimated_prompt_chars']];oldred=[x['old_estimated_prompt_chars']-x['estimated_prompt_chars'] for x in prompts if x['old_estimated_prompt_chars']];oldrates=[(x['old_estimated_prompt_chars']-x['estimated_prompt_chars'])/x['old_estimated_prompt_chars'] for x in prompts if x['old_estimated_prompt_chars']];ctxred=[x['context_id_estimated_prompt_chars']-x['estimated_prompt_chars'] for x in prompts if x['context_id_estimated_prompt_chars']];ctxrates=[(x['context_id_estimated_prompt_chars']-x['estimated_prompt_chars'])/x['context_id_estimated_prompt_chars'] for x in prompts if x['context_id_estimated_prompt_chars']];nt=[x['num_target_meds'] for x in prompts];ni=[x['num_context_ids'] for x in prompts]
 quality={'api_not_called':True,'dry_run_only':True,'uses_min_token_context_id_strings':True,'no_id_text_object_format':counts['id_text_object_found']==0,'no_candidate_anchors_field':counts['legacy_anchor_field_found']==0,'no_allowed_anchor_ids_field':counts['legacy_allowed_ids_field_found']==0,'llm_outputs_anchor_id_only':not any(x['problem_type']=='missing_anchor_output_constraint' for x in problems) and counts['plural_anchor_ids_field_found']==0,'anchor_id_must_come_from_context':counts['missing_anchor_id_constraint']==0,'anchor_id_map_available_for_postprocessing':not any(x['problem_type'] in {'anchor_id_map_incomplete','single_restore_failed','null_restore_failed','plural_schema_error_not_detected'} for x in problems),'target_medications_pipe_format':not any(x['problem_type']=='invalid_target_pipe' for x in problems),'no_condition_group':counts['forbidden_field_found']==0,'safe_prompt_constraints_present':counts['missing_json_only_constraint']==counts['missing_prescribing_intent_warning']==0,'ready_for_real_deepseek_call':not problems}
 single_check={'single_anchor_required':True,'anchor_id_field_used':counts['missing_anchor_id_constraint']==0,'anchor_ids_array_forbidden':counts['plural_anchor_ids_field_found']==0 and not any(x['problem_type']=='plural_schema_error_not_detected' for x in problems),'max_one_anchor_per_medication':not any(x['problem_type'] in {'missing_anchor_output_constraint','single_restore_failed'} for x in problems),'restored_anchor_length_lte_1':not any(x['problem_type'] in {'single_restore_failed','null_restore_failed'} for x in problems)}
 report={'experiment_name':'deepseek_l3_test20_dx_px_nonempty_min_token_prompt_audit','dry_run_only':True,'api_called':False,'input_files_used':{'selected_20_cases':str(SELECTED.relative_to(ROOT)) if used else None,'dx_px_nonempty_source':str(SOURCE.relative_to(ROOT)),'old_prompt':str(OLD.relative_to(ROOT)) if OLD.exists() else None,'compact_prompt':str(COMPACT.relative_to(ROOT)) if COMPACT.exists() else None,'context_id_prompt':str(CONTEXT_ID.relative_to(ROOT)) if CONTEXT_ID.exists() else None},'output_dir':str(OUT.relative_to(ROOT)),'num_cases':20,'num_prompts':20,'prompt_compaction':{'old_prompt_file_available':OLD.exists(),'compact_prompt_file_available':COMPACT.exists(),'context_id_prompt_file_available':CONTEXT_ID.exists(),'old_estimated_prompt_chars_mean':statistics.mean(oldvals) if oldvals else 0,'compact_estimated_prompt_chars_mean':statistics.mean(compactvals) if compactvals else 0,'context_id_estimated_prompt_chars_mean':statistics.mean(contextvals) if contextvals else 0,'min_token_estimated_prompt_chars_mean':statistics.mean(chars),'mean_char_reduction_vs_old':statistics.mean(oldred) if oldred else 0,'mean_char_reduction_rate_vs_old':statistics.mean(oldrates) if oldrates else 0.0,'mean_char_reduction_vs_context_id':statistics.mean(ctxred) if ctxred else 0,'mean_char_reduction_rate_vs_context_id':statistics.mean(ctxrates) if ctxrates else 0.0},'case_stats':{'num_target_meds_mean':statistics.mean(nt),'num_target_meds_max':max(nt),'num_context_ids_mean':statistics.mean(ni),'num_context_ids_max':max(ni),'num_dx_mean':statistics.mean(x['num_dx'] for x in prompts),'num_px_mean':statistics.mean(x['num_px'] for x in prompts),'num_lab_mean':statistics.mean(x['num_lab'] for x in prompts)},'problem_counts':{'empty_dx_cases':counts['empty_dx'],'empty_px_cases':counts['empty_px'],'empty_med_cases':counts['empty_med'],'empty_target_med_cases':counts['empty_target_med'],'empty_context_id_cases':counts['empty_context_id'],'duplicate_context_id_cases':counts['duplicate_context_id'],'condition_group_prompt_cases':counts['forbidden_field_found'],'candidate_anchors_field_cases':counts['legacy_anchor_field_found'],'allowed_anchor_ids_field_cases':counts['legacy_allowed_ids_field_found'],'anchor_ids_field_cases':counts['plural_anchor_ids_field_found'],'id_text_object_cases':counts['id_text_object_found'],'missing_anchor_id_constraint_cases':counts['missing_anchor_id_constraint'],'missing_json_only_constraint_cases':counts['missing_json_only_constraint'],'missing_prescribing_intent_warning_cases':counts['missing_prescribing_intent_warning']},'single_anchor_check':single_check,'quality_check':quality,'warnings':[]}
 REPORT.write_text(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False),encoding='utf-8')
 md=['# Min-Token Prompt Audit Sample','']
 for i,p in enumerate(prompts[:3],1):
  oldrate=(p['old_estimated_prompt_chars']-p['estimated_prompt_chars'])/p['old_estimated_prompt_chars'] if p['old_estimated_prompt_chars'] else 0;ctxrate=(p['context_id_estimated_prompt_chars']-p['estimated_prompt_chars'])/p['context_id_estimated_prompt_chars'] if p['context_id_estimated_prompt_chars'] else 0
  md += [f'## Prompt {i}','','### Metadata',f"- stay_id: {p['stay_id']}",f"- hospital_id: {p['hospital_id']}",f"- old chars: {p['old_estimated_prompt_chars']}",f"- context-id chars: {p['context_id_estimated_prompt_chars']}",f"- min-token chars: {p['estimated_prompt_chars']}",f"- reduction rate vs old: {oldrate:.2%}",f"- reduction rate vs context-id: {ctxrate:.2%}",f"- num_dx: {p['num_dx']}",f"- num_px: {p['num_px']}",f"- num_lab: {p['num_lab']}",f"- num_context_ids: {p['num_context_ids']}",f"- num_target_meds: {p['num_target_meds']}",'','### Context','',json.dumps(p['context'],ensure_ascii=False,indent=2),'','### System Prompt','',p['system_prompt'],'','### User Prompt','','```json',json.dumps(json.loads(p['user_prompt']),ensure_ascii=False,indent=2),'```','']
 SAMPLE.write_text('\n'.join(md),encoding='utf-8')
 reread=[json.loads(x) for x in PROMPTS.read_text(encoding='utf-8').splitlines() if x.strip()];assert len(reread)==20 and all(x['dry_run_only'] and x['system_prompt'] and x['user_prompt'] and x['target_medications'] and x['context']['dx'] and x['context']['px'] for x in reread);assert quality['ready_for_real_deepseek_call'];assert not OLD.exists() or report['prompt_compaction']['mean_char_reduction_rate_vs_old']>0;assert sha(SOURCE)==source_hash and (not used or sha(SELECTED)==selected_hash)
 print('DeepSeek L3 min-token prompt dry-run audit completed')
if __name__=='__main__':main()
